apiVersion: v1
kind: Service
metadata:
  labels:
    component: api-cluster-ip
  name: movie-api-cluster-ip
spec:
  type: LoadBalancer
  selector:
    component: backend
  ports:
  - port: 80
    targetPort: 80
